### ISSUE TITLE
Evaluation on the TSPLIB200-1000

### ISSUE THREAD

**Issue by gaocrr** [Thinklab-SJTU/T2TCO#1]
Dear authors, thanks for your excellent research. When I tried to reproduce your experiments on TSPLIB, I found that the optimal solutions provided in the data/tsp/tsplib200-1000.txt may be wrong since they are just 1,2,3,...,n,1 and their cost are quite high.

**Comment by yangco-le** [comment]
Hi @gaocrr, 

Thank you for your interest in our work. Apologies for the oversight, and we have now updated `data/tsp/tsplib200-1000.txt`. It's worth noting that the reference solutions are generated using lkh3. Additionally, we have included the preprocessing code for tsplib data in `data/tsplib`.

Should you have any further inquiries, please feel free to reach out.

**Comment by gaocrr** [comment]
Thanks for your response. I think the issue has been solved.
